import { GeofenceSite, NotificationItem, PunchRecord, UserProfile } from '../types';

export const OFFICIAL_SELFIE_URL = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCljyXsmNiIH1HKcs2u-b8Q4ZbQPid0jblqrsrg0z0ocODfet7kocM_-JCecnTW8FHfdwliDb0Zb1___5OzZwMWJCf_qB6bJjUWwycMYfYEoHiCrL6-FEA_YHfk75tg5UdewyLs7AVed-hhZcyPFvyUTTz8dLxiK_Z4c3O3M68Ov_72wKH2iNSUWFFIUu80k2kJx4-ZD9oZZ3YgXwtpDSL_DxlyoPHvn6DwgGVfC10GLURb2CGXP8wxiA';

export const initialProfile: UserProfile = {
  id: 'emp-1',
  role: 'employee',
  name: 'Sarah Chen',
  email: 'sarah.chen@sqattend.com',
  phone: '+1 555 234 5678',
  password: 'password123',
  title: 'Senior Enterprise Architect',
  employeeId: 'SQ-8842',
  department: 'Cloud & Infrastructure Systems',
  shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Late Cutoff: 09:30 AM)',
  dailyWorkingHours: 9.0,
  monthlySalary: 10000, // 10k default salary
  weeklyTargetHours: 45,
  hoursCompletedThisWeek: 31.8,
  monthlyLateArrivalsCount: 1, // 1 of 3 acceptable grace days used
  halfDaysCount: 0,
  shiftStartTime: '09:00 AM',
  shiftEndTime: '06:00 PM',
  lateThresholdTime: '09:30 AM',
  maxAllowedLateDaysPerMonth: 3,
  avatarUrl: OFFICIAL_SELFIE_URL,
  biometricEnrolledDate: 'Oct 14, 2025 • SHA256-v2',
  biometricConfidence: 99.4,
  biometricHash: '8f92b7c4d1e039aa50284c8310b91e77',
  biometricOptional: true,
  biometricEnabled: false, // Default: Face ID is optional & disabled by default
  isGeofenceEnforced: true,
};

export const admin1: UserProfile = {
  id: 'admin-1',
  role: 'admin',
  name: 'David Vance',
  email: 'admin1@sqattend.com',
  phone: '+1 555 100 2001',
  password: 'password123',
  title: 'HR & Operations Admin (1 of 5)',
  employeeId: 'SQ-ADMIN-1',
  department: 'Executive Administration & HR',
  shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Admin Clearance)',
  dailyWorkingHours: 9.0,
  monthlySalary: 10000,
  weeklyTargetHours: 45,
  hoursCompletedThisWeek: 45.0,
  monthlyLateArrivalsCount: 0,
  halfDaysCount: 0,
  shiftStartTime: '09:00 AM',
  shiftEndTime: '06:00 PM',
  lateThresholdTime: '09:30 AM',
  maxAllowedLateDaysPerMonth: 3,
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
  biometricEnrolledDate: 'Admin Key 1 • Calibrated',
  biometricConfidence: 99.9,
  biometricHash: 'admin-key-01',
  biometricOptional: true,
  biometricEnabled: false,
  isGeofenceEnforced: false,
};

export const admin2: UserProfile = {
  id: 'admin-2',
  role: 'admin',
  name: 'Marcus Wright',
  email: 'admin2@sqattend.com',
  phone: '+1 555 100 2002',
  password: 'password123',
  title: 'Security & Compliance Admin (2 of 5)',
  employeeId: 'SQ-ADMIN-2',
  department: 'Security & Telemetry Audit',
  shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Admin Clearance)',
  dailyWorkingHours: 9.0,
  monthlySalary: 10000,
  weeklyTargetHours: 45,
  hoursCompletedThisWeek: 45.0,
  monthlyLateArrivalsCount: 0,
  halfDaysCount: 0,
  shiftStartTime: '09:00 AM',
  shiftEndTime: '06:00 PM',
  lateThresholdTime: '09:30 AM',
  maxAllowedLateDaysPerMonth: 3,
  avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
  biometricEnrolledDate: 'Admin Key 2 • Calibrated',
  biometricConfidence: 99.9,
  biometricHash: 'admin-key-02',
  biometricOptional: true,
  biometricEnabled: false,
  isGeofenceEnforced: false,
};

export const admin3: UserProfile = {
  id: 'admin-3',
  role: 'admin',
  name: 'Priya Patel',
  email: 'admin3@sqattend.com',
  phone: '+1 555 100 2003',
  password: 'password123',
  title: 'Workforce Logistics Admin (3 of 5)',
  employeeId: 'SQ-ADMIN-3',
  department: 'Workforce & Facilities Management',
  shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Admin Clearance)',
  dailyWorkingHours: 9.0,
  monthlySalary: 10000,
  weeklyTargetHours: 45,
  hoursCompletedThisWeek: 45.0,
  monthlyLateArrivalsCount: 0,
  halfDaysCount: 0,
  shiftStartTime: '09:00 AM',
  shiftEndTime: '06:00 PM',
  lateThresholdTime: '09:30 AM',
  maxAllowedLateDaysPerMonth: 3,
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
  biometricEnrolledDate: 'Admin Key 3 • Calibrated',
  biometricConfidence: 99.9,
  biometricHash: 'admin-key-03',
  biometricOptional: true,
  biometricEnabled: false,
  isGeofenceEnforced: false,
};

export const admin4: UserProfile = {
  id: 'admin-4',
  role: 'admin',
  name: 'Elena Rostova',
  email: 'admin4@sqattend.com',
  phone: '+1 555 100 2004',
  password: 'password123',
  title: 'Systems & Payroll Admin (4 of 5)',
  employeeId: 'SQ-ADMIN-4',
  department: 'Finance & Payroll Systems',
  shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Admin Clearance)',
  dailyWorkingHours: 9.0,
  monthlySalary: 10000,
  weeklyTargetHours: 45,
  hoursCompletedThisWeek: 45.0,
  monthlyLateArrivalsCount: 0,
  halfDaysCount: 0,
  shiftStartTime: '09:00 AM',
  shiftEndTime: '06:00 PM',
  lateThresholdTime: '09:30 AM',
  maxAllowedLateDaysPerMonth: 3,
  avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
  biometricEnrolledDate: 'Admin Key 4 • Calibrated',
  biometricConfidence: 99.9,
  biometricHash: 'admin-key-04',
  biometricOptional: true,
  biometricEnabled: false,
  isGeofenceEnforced: false,
};

export const admin5: UserProfile = {
  id: 'admin-5',
  role: 'admin',
  name: 'Kevin Zhao',
  email: 'admin5@sqattend.com',
  phone: '+1 555 100 2005',
  password: 'password123',
  title: 'Site Operations Admin (5 of 5)',
  employeeId: 'SQ-ADMIN-5',
  department: 'Field & Operations Command',
  shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Admin Clearance)',
  dailyWorkingHours: 9.0,
  monthlySalary: 10000,
  weeklyTargetHours: 45,
  hoursCompletedThisWeek: 45.0,
  monthlyLateArrivalsCount: 0,
  halfDaysCount: 0,
  shiftStartTime: '09:00 AM',
  shiftEndTime: '06:00 PM',
  lateThresholdTime: '09:30 AM',
  maxAllowedLateDaysPerMonth: 3,
  avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
  biometricEnrolledDate: 'Admin Key 5 • Calibrated',
  biometricConfidence: 99.9,
  biometricHash: 'admin-key-05',
  biometricOptional: true,
  biometricEnabled: false,
  isGeofenceEnforced: false,
};

export const adminUser = admin1;

export const ownerUser: UserProfile = {
  id: 'owner-1',
  role: 'owner',
  name: 'Farhan Qamar',
  email: 'owner@sqattend.com',
  phone: '+1 555 900 8000',
  password: 'password123',
  title: 'Managing Director & Firm Owner',
  employeeId: 'SQ-OWNER',
  department: 'Executive Board',
  shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Owner Clearance)',
  dailyWorkingHours: 9.0,
  monthlySalary: 10000, // 10k default salary, customizable by Admin/Owner
  weeklyTargetHours: 45,
  hoursCompletedThisWeek: 45.0,
  monthlyLateArrivalsCount: 0,
  halfDaysCount: 0,
  shiftStartTime: '09:00 AM',
  shiftEndTime: '06:00 PM',
  lateThresholdTime: '09:30 AM',
  maxAllowedLateDaysPerMonth: 3,
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
  biometricEnrolledDate: 'Executive Owner Key',
  biometricConfidence: 99.9,
  biometricHash: 'owner-master-key-01',
  biometricOptional: true,
  biometricEnabled: false,
  isGeofenceEnforced: false,
};

export const sampleEmployees: UserProfile[] = [
  initialProfile,
  {
    id: 'emp-2',
    role: 'employee',
    name: 'Alex Rivera',
    email: 'alex.rivera@sqattend.com',
    phone: '+1 555 987 6543',
    password: 'password123',
    title: 'Operations Director',
    employeeId: 'SQ-7721',
    department: 'Field Logistics & Deployment',
    shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Late Cutoff: 09:30 AM)',
    dailyWorkingHours: 8.0,
    monthlySalary: 10000, // 10k default salary
    weeklyTargetHours: 40.0,
    hoursCompletedThisWeek: 34.0,
    monthlyLateArrivalsCount: 2, // 2 of 3 grace days used
    halfDaysCount: 0,
    shiftStartTime: '09:00 AM',
    shiftEndTime: '06:00 PM',
    lateThresholdTime: '09:30 AM',
    maxAllowedLateDaysPerMonth: 3,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    biometricEnrolledDate: 'Nov 02, 2025 • Calibrated 3D',
    biometricConfidence: 99.1,
    biometricHash: '4a19b8820f12d8a4192b0c441',
    biometricOptional: true,
    biometricEnabled: false,
    isGeofenceEnforced: true,
  },
  {
    id: 'emp-3',
    role: 'employee',
    name: 'Athar Qamar',
    email: 'athar.qamar@sqattend.com',
    phone: '+1 555 731 7000',
    password: 'password123',
    title: 'Principal Systems Engineer',
    employeeId: 'SQ-9104',
    department: 'Engineering & DevOps',
    shiftWindow: 'Locked Shift: 09:00 AM – 06:00 PM (Late Cutoff: 09:30 AM)',
    dailyWorkingHours: 8.0,
    monthlySalary: 10000, // 10k default salary
    weeklyTargetHours: 40,
    hoursCompletedThisWeek: 36.5,
    monthlyLateArrivalsCount: 3, // 3 of 3 grace days used - next late entry is Half Day!
    halfDaysCount: 0,
    shiftStartTime: '09:00 AM',
    shiftEndTime: '06:00 PM',
    lateThresholdTime: '09:30 AM',
    maxAllowedLateDaysPerMonth: 3,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    biometricEnrolledDate: 'Jan 10, 2026 • Verified',
    biometricConfidence: 99.7,
    biometricHash: '8e20f19934ba77c1029e84',
    biometricOptional: true,
    biometricEnabled: true,
    isGeofenceEnforced: true,
  },
  admin1,
  admin2,
  admin3,
  admin4,
  admin5,
  ownerUser
];

export const initialSites: GeofenceSite[] = [
  {
    id: 'site-402',
    code: 'Site #402',
    name: 'HQ Tech Park',
    zone: 'Zone B - Glass Atrium',
    address: '100 Silicon Way, Building 4, Floor 2',
    radiusMeters: 50, // 50m firm radius
    coordinates: {
      lat: 37.7749,
      lng: -122.4194,
    },
    isActive: true,
  },
  {
    id: 'site-208',
    code: 'Site #208',
    name: 'Downtown Financial Hub',
    zone: 'Tower East - Suite 1400',
    address: '450 Montgomery St, San Francisco, CA',
    radiusMeters: 50, // 50m firm radius
    coordinates: {
      lat: 37.7922,
      lng: -122.4019,
    },
    isActive: false,
  },
  {
    id: 'site-501',
    code: 'Site #501',
    name: 'R&D Innovation Lab',
    zone: 'Hardware Hangar 3',
    address: '1200 Innovation Blvd, Sunnyvale, CA',
    radiusMeters: 50, // 50m firm radius
    coordinates: {
      lat: 37.3861,
      lng: -122.0839,
    },
    isActive: false,
  },
];

export const initialPunches: PunchRecord[] = [
  {
    id: 'punch-105',
    employeeId: 'SQ-7721',
    employeeName: 'Alex Rivera',
    type: 'field-work-start',
    timestamp: '2026-09-24T10:15:00Z',
    timeFormatted: '10:15:00 AM',
    dateFormatted: 'Today • Sep 24',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park (Field Duty)',
    zone: 'Client Technical Briefing',
    accuracy: '±3.8m',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    confidence: 99.1,
    statusTag: 'Approved',
    hash: 'sha256-alex-fw-1',
    synced: true,
    isFieldWork: true,
    fieldWorkPurpose: 'On-Site Client Server Rack Delivery',
    countsAsWorkTime: true,
  },
  {
    id: 'punch-104',
    employeeId: 'SQ-8842',
    employeeName: 'Sarah Chen',
    type: 'clock-in',
    timestamp: '2026-09-24T09:14:20Z',
    timeFormatted: '09:14:20 AM',
    dateFormatted: 'Today • Sep 24',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park',
    zone: 'Zone B',
    accuracy: '±3.8m',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    confidence: 99.4,
    photoUrl: OFFICIAL_SELFIE_URL,
    statusTag: 'On Time',
    hash: 'sha256-4cf89a2b9101',
    synced: true,
  },
  {
    id: 'punch-103b',
    employeeId: 'SQ-9104',
    employeeName: 'Athar Qamar',
    type: 'clock-in',
    timestamp: '2026-09-24T08:55:10Z',
    timeFormatted: '08:55:10 AM',
    dateFormatted: 'Today • Sep 24',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park',
    zone: 'Zone B',
    accuracy: '±3.2m',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    confidence: 99.7,
    statusTag: 'Early',
    hash: 'sha256-athar-in-1',
    synced: true,
  },
  {
    id: 'punch-103',
    employeeId: 'SQ-8842',
    employeeName: 'Sarah Chen',
    type: 'clock-out',
    timestamp: '2026-09-23T18:42:05Z',
    timeFormatted: '06:42:05 PM',
    dateFormatted: 'Wed • Sep 23',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park',
    zone: 'Zone B',
    accuracy: '±4.1m',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    confidence: 99.2,
    photoUrl: OFFICIAL_SELFIE_URL,
    statusTag: 'On Time',
    hash: 'sha256-91e843c09bb2',
    synced: true,
  },
  {
    id: 'punch-102-auto',
    employeeId: 'SQ-7721',
    employeeName: 'Alex Rivera',
    type: 'auto-clock-out',
    timestamp: '2026-09-23T19:05:00Z',
    timeFormatted: '07:05:00 PM',
    dateFormatted: 'Wed • Sep 23',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park',
    zone: 'Zone B',
    accuracy: '±4.8m',
    coordinates: { lat: 37.7780, lng: -122.4220 },
    confidence: 98.8,
    statusTag: 'Approved',
    hash: 'sha256-auto-exit-alex',
    synced: true,
    isAutoPunchOut: true,
    autoPunchReason: 'Auto Punch-Out: Employee outside firm > 1 hour after 7:00 PM evening without manual punch-out.',
  },
  {
    id: 'punch-102',
    employeeId: 'SQ-8842',
    employeeName: 'Sarah Chen',
    type: 'break-end',
    timestamp: '2026-09-23T14:00:20Z',
    timeFormatted: '02:00:20 PM',
    dateFormatted: 'Wed • Sep 23',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park',
    zone: 'Zone B',
    accuracy: '±3.5m',
    coordinates: { lat: 37.7750, lng: -122.4193 },
    confidence: 99.6,
    photoUrl: OFFICIAL_SELFIE_URL,
    statusTag: 'On Time',
    hash: 'sha256-3b71ca8401ef',
    synced: true,
  },
  {
    id: 'punch-101',
    employeeId: 'SQ-8842',
    employeeName: 'Sarah Chen',
    type: 'break-start',
    timestamp: '2026-09-23T13:00:44Z',
    timeFormatted: '01:00:44 PM',
    dateFormatted: 'Wed • Sep 23',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park',
    zone: 'Zone B',
    accuracy: '±3.6m',
    coordinates: { lat: 37.7749, lng: -122.4195 },
    confidence: 99.3,
    photoUrl: OFFICIAL_SELFIE_URL,
    statusTag: 'Approved',
    hash: 'sha256-118dfa7322ab',
    synced: true,
  },
  {
    id: 'punch-100',
    employeeId: 'SQ-8842',
    employeeName: 'Sarah Chen',
    type: 'clock-in',
    timestamp: '2026-09-23T09:30:10Z',
    timeFormatted: '09:30:10 AM',
    dateFormatted: 'Wed • Sep 23',
    siteId: 'Site #402',
    siteName: 'HQ Tech Park',
    zone: 'Zone B',
    accuracy: '±3.2m',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    confidence: 99.5,
    photoUrl: OFFICIAL_SELFIE_URL,
    statusTag: 'On Time',
    hash: 'sha256-5ea211f4d909',
    synced: true,
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Geofence Perimeter Entered',
    message: 'Welcome to HQ Tech Park • Zone B. GPS Lock established with ±3.8m precision.',
    timeAgo: '12m ago',
    type: 'geofence',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Shift Window Active',
    message: 'Standard 8h 00m shift is now active. Morning punch registered successfully.',
    timeAgo: '2h ago',
    type: 'shift',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Timesheet Approved',
    message: 'Manager David Vance signed off on Week 38 timesheet (40.2h verified).',
    timeAgo: 'Yesterday',
    type: 'approval',
    read: true,
  },
];
